services:
  - type: web
    name: teknikdepo
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
